"""
Automated Retail Sales Reporting System
Author  : Anil Dangi
Contact : anildangi18@gmail.com
LinkedIn: https://www.linkedin.com/in/anil-dangi-1a84623a9/
Purpose : Freelance-ready automated sales analytics
"""

import pandas as pd
import os
from datetime import datetime

# =========================
# CONFIGURATION
# =========================
INPUT_FILE = "data/retail_sales.csv"
OUTPUT_DIR = "output"
OUTPUT_FILE = "top_10_cities_sales.csv"

AUTHOR_NAME = "Anil Dangi"

# =========================
# CREATE OUTPUT DIRECTORY
# =========================
os.makedirs(OUTPUT_DIR, exist_ok=True)

# =========================
# LOAD DATA
# =========================
try:
    df = pd.read_csv(INPUT_FILE)
except FileNotFoundError:
    raise FileNotFoundError(
        f"Input file not found: {INPUT_FILE}. "
        "Please place your sales CSV inside the data/ folder."
    )

# =========================
# VALIDATE REQUIRED COLUMNS
# =========================
required_columns = {"City", "Sales"}
missing_columns = required_columns - set(df.columns)

if missing_columns:
    raise ValueError(f"Missing required columns: {missing_columns}")

# =========================
# DATA CLEANING
# =========================
df["Sales"] = pd.to_numeric(df["Sales"], errors="coerce")
df = df.dropna(subset=["City", "Sales"])

# =========================
# AGGREGATION
# =========================
city_sales = (
    df.groupby("City", as_index=False)["Sales"]
    .sum()
    .sort_values(by="Sales", ascending=False)
    .head(10)
)

# =========================
# SAVE OUTPUT WITH WATERMARK
# =========================
output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILE)

with open(output_path, "w", encoding="utf-8") as f:
    f.write(f"# Generated by: {AUTHOR_NAME}\n")
    f.write("# Project: Automated Retail Sales Reporting System\n")
    f.write(f"# Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    f.write("# ---------------------------------------------\n")

city_sales.to_csv(output_path, mode="a", index=False)

# =========================
# SUCCESS MESSAGE
# =========================
print("✅ Top 10 Cities Sales Report Generated Successfully!")
print(f"📁 Output file saved at: {output_path}")
print(f"🛡️ Watermark applied: Generated by {AUTHOR_NAME}")
